#mysql
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3306/easyproject?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model

server:
  port: 9000